package com.maintenance.management;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/submit-maintenance")
public class MaintenanceServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    private String jdbcUrl = "jdbc:mysql://localhost:3307/condo?useSSL=false";
    private String jdbcUsername = "root";
    private String jdbcPassword = "";

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        try (Connection connection = DriverManager.getConnection(jdbcUrl, jdbcUsername, jdbcPassword)) {
            MaintenanceDao maintenanceDAO = new MaintenanceDao(connection);
            
            String unitNumber = request.getParameter("unitNumber");
            String status = request.getParameter("status");
            String description = request.getParameter("description");

            // Set the default request status to "pending"
            String requestStatus = "pending";

            // Assuming you're not passing the id from the form
            // If the id is auto-generated by the database, you can omit it here
            int id = 0; // Replace with the appropriate id value

            MaintenanceRequest maintenanceRequest = new MaintenanceRequest(id, unitNumber, status, description, requestStatus);

            maintenanceDAO.addMaintenanceRequest(maintenanceRequest);
        } catch (SQLException e) {
            // Handle database-related exceptions
            e.printStackTrace();
        }

        response.sendRedirect(request.getContextPath() + "/maintenance-form.jsp");
    }
}
